"""Merge final labels, raw post text, image existence, and OCR results.

The output is one row per unique post from final_labels.csv, including posts
that do not have images.
"""

from __future__ import annotations

import argparse
import ast
from pathlib import Path

import pandas as pd


OUTPUT_COLUMNS = [
    "post_id",
    "label",
    "raw_post_text",
    "image_exists",
    "ocr_text",
    "ocr_readable",
]


def parse_args() -> argparse.Namespace:
    project_root = Path(__file__).resolve().parents[1]
    datasets_dir = project_root / "datasets"
    data_dir = datasets_dir / "online-misogyny-eacl2021-main" / "data"

    parser = argparse.ArgumentParser(
        description="Build a compact one-row-per-post dataset with OCR fields."
    )
    parser.add_argument(
        "--final-labels",
        type=Path,
        default=data_dir / "final_labels.csv",
        help="Path to final_labels.csv.",
    )
    parser.add_argument(
        "--image-dir",
        type=Path,
        default=data_dir / "dataset_post_images",
        help="Directory containing post image files.",
    )
    parser.add_argument(
        "--ocr-results",
        type=Path,
        default=project_root / ".easyocr" / "ocr_results.csv",
        help="Path to OCR results generated by generate_ocr_results.py.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=datasets_dir / "post_ocr_dataset.csv",
        help="Output CSV path.",
    )
    return parser.parse_args()


def parse_bool(value: object) -> bool:
    if isinstance(value, bool):
        return value
    return str(value).strip().casefold() in {"1", "true", "yes", "y"}


def parse_top_sheet_order(value: object) -> int | None:
    """Return the first integer from sheet_order strings such as '(12, 2, 1)'."""
    try:
        parsed = ast.literal_eval(str(value))
    except (SyntaxError, ValueError):
        return None
    if not isinstance(parsed, tuple) or not parsed:
        return None
    try:
        return int(parsed[0])
    except (TypeError, ValueError):
        return None


def collapse_label(labels: pd.Series) -> str:
    values = sorted({str(label).strip() for label in labels if str(label).strip()})
    if len(values) == 1:
        return values[0]
    return "Conflict: " + " + ".join(values)


def unique_nonempty_values(values: pd.Series) -> list[str]:
    unique: list[str] = []
    seen: set[str] = set()
    for value in values:
        text = str(value).strip()
        if not text or text in seen:
            continue
        unique.append(text)
        seen.add(text)
    return unique


def merge_unique_text(values: pd.Series) -> str:
    return "\n".join(unique_nonempty_values(values))


def raw_text_from_row(row: pd.Series) -> str:
    body = str(row.get("body", "")).strip()
    image_value = str(row.get("image", "")).strip()

    # In a few source rows, a comma split the tail of the post text into the
    # image column. Recover that fragment while keeping normal image markers out.
    if image_value and image_value.casefold() != "yes":
        return f"{body}, {image_value}" if body else image_value
    return body


def build_expected_image_file(row: pd.Series) -> str:
    if not row["image_flag"]:
        return ""
    top_order = parse_top_sheet_order(row["sheet_order"])
    if top_order is None:
        return ""
    return f"{row['week']}_{row['group']}_{top_order}.jpg"


def load_ocr_results(path: Path) -> dict[str, dict[str, object]]:
    if not path.exists():
        return {}

    ocr = pd.read_csv(path, keep_default_na=False)
    for column in ["file", "ocr_success", "has_readable_text", "ocr_text_clean", "ocr_text"]:
        if column not in ocr.columns:
            ocr[column] = ""

    ocr["ocr_success"] = ocr["ocr_success"].map(parse_bool)
    ocr["has_readable_text"] = ocr["has_readable_text"].map(parse_bool)
    ocr = ocr.drop_duplicates("file", keep="last")
    return ocr.set_index("file").to_dict(orient="index")


def ocr_text_for_files(files: list[str], ocr_by_file: dict[str, dict[str, object]]) -> str:
    pieces: list[str] = []
    seen: set[str] = set()
    for file_name in files:
        row = ocr_by_file.get(file_name)
        if not row or not parse_bool(row.get("ocr_success", False)):
            continue
        text = str(row.get("ocr_text_clean", "")).strip() or str(row.get("ocr_text", "")).strip()
        if text and text not in seen:
            pieces.append(text)
            seen.add(text)
    return "\n".join(pieces)


def ocr_readable_for_files(files: list[str], ocr_by_file: dict[str, dict[str, object]]) -> bool:
    return any(parse_bool(ocr_by_file.get(file_name, {}).get("has_readable_text", False)) for file_name in files)


def validate_columns(df: pd.DataFrame, path: Path) -> None:
    required = {"entry_id", "body", "image", "week", "group", "sheet_order", "level_1"}
    missing = sorted(required - set(df.columns))
    if missing:
        raise ValueError(f"{path} is missing required columns: {', '.join(missing)}")


def main() -> None:
    args = parse_args()

    labels = pd.read_csv(args.final_labels, keep_default_na=False)
    validate_columns(labels, args.final_labels)

    labels["image_flag"] = labels["image"].astype(str).str.strip().str.casefold().eq("yes")
    labels["raw_post_text_candidate"] = labels.apply(raw_text_from_row, axis=1)
    labels["expected_image_file"] = labels.apply(build_expected_image_file, axis=1)

    grouped = (
        labels.groupby("entry_id", sort=False)
        .agg(
            label=("level_1", collapse_label),
            raw_post_text=("raw_post_text_candidate", merge_unique_text),
            expected_image_files=("expected_image_file", unique_nonempty_values),
        )
        .reset_index()
        .rename(columns={"entry_id": "post_id"})
    )

    ocr_by_file = load_ocr_results(args.ocr_results)

    grouped["image_exists"] = grouped["expected_image_files"].map(
        lambda files: any((args.image_dir / file_name).exists() for file_name in files)
    )
    grouped["ocr_text"] = grouped["expected_image_files"].map(
        lambda files: ocr_text_for_files(files, ocr_by_file)
    )
    grouped["ocr_readable"] = grouped["expected_image_files"].map(
        lambda files: ocr_readable_for_files(files, ocr_by_file)
    )

    output = grouped[OUTPUT_COLUMNS]
    args.output.parent.mkdir(parents=True, exist_ok=True)
    output.to_csv(args.output, index=False)

    print(f"Wrote {len(output):,} posts to {args.output}")
    print(f"Posts with existing image files: {int(output['image_exists'].sum()):,}")
    print(f"Posts with readable OCR: {int(output['ocr_readable'].sum()):,}")


if __name__ == "__main__":
    main()
